<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://192.168.241.200:3001/updatestatus" ID="_vKrZAN5REeeQLatJAiSUkQ">
  <rest:operation verb="PUT" name="closeReopenCase" ID="_yJtV8N5REeeQLatJAiSUkQ" restservice_type="json">
    <rest:input type="project:///Schemas/integrations/CaseCloseReopen.xsd?xsdelement={__project:///Schemas/integrations/CaseCloseReopen.xsd}iob_request_root" name="body" headerDirection="request" contentType="application/json" requestRootElement="true" ID="_ycVXAN5REeeQLatJAiSUkQ"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="response" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_yJtV8d5REeeQLatJAiSUkQ"/>
  </rest:operation>
</rest:descriptor>