<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://192.168.241.200:3001/createactivity" ID="_WdAcwLCbEeeBPdzJIpWARQ">
  <rest:operation verb="POST" name="Create Activity" ID="_WdAcwbCbEeeBPdzJIpWARQ" restservice_type="json">
    <rest:input type="project:///Schemas/integrations/createActivity.xsd?xsdelement={__project:///Schemas/integrations/createActivity.xsd}iob_request_root" name="body" headerDirection="request" contentType="application/json" requestRootElement="true" ID="_WdAcwrCbEeeBPdzJIpWARQ"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="response" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_WdAcw7CbEeeBPdzJIpWARQ"/>
  </rest:operation>
</rest:descriptor>