<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://bpms.everteam.us:3002/api/generateIQBatch" ID="_yoWogNlpEeewm9Q6LNzzXQ">
  <rest:operation verb="POST" name="POST" ID="_yoXPk9lpEeewm9Q6LNzzXQ" restservice_type="json">
    <rest:input type="project:///Schemas/integrations/generateIQBatch.xsd?xsdelement={http://www.example.org/generateIQBatch}iob_request_root" name="body" headerDirection="request" contentType="application/json" requestRootElement="true" ID="_yoXPlNlpEeewm9Q6LNzzXQ"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="response" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_yoXPldlpEeewm9Q6LNzzXQ"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="EnvironmentId" headerDirection="request" contentType="text/xml" ID="_te81YNxAEeewLbkmzYmScw"/>
</rest:descriptor>