<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://bpms.everteam.us:3002/api/generateFile?environmentid={EnvironmentId}" ID="_PjUxULBdEeeJLNNIwabO_g">
  <rest:operation verb="POST" name="Generate File" ID="_PjVYYLBdEeeJLNNIwabO_g" restservice_type="json">
    <rest:input type="project:///Schemas/integrations/generateFile.xsd?xsdelement={__project:///Schemas/integrations/generateFile.xsd}iob_request_root" name="body" headerDirection="request" contentType="application/json" requestRootElement="true" ID="_PjVYYbBdEeeJLNNIwabO_g"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="response" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_PjVYYrBdEeeJLNNIwabO_g"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="EnvironmentId" headerDirection="request" contentType="text/xml" ID="_hZRkYNw9EeewLbkmzYmScw"/>
</rest:descriptor>