<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://localhost:3001/api/activities/{case-id}" ID="_ET9HYMguEee1Nq_BV80-Og">
  <rest:operation verb="GET" name="GET" ID="_ET9uccguEee1Nq_BV80-Og" restservice_type="json">
    <rest:output type="project:///Schemas/IQ.xsd?xsdelement={http://www.example.org/IQ}Activities" name="response" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_ET9ucsguEee1Nq_BV80-Og"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="case-id" headerDirection="request" contentType="text/xml" ID="_ET9ucMguEee1Nq_BV80-Og"/>
</rest:descriptor>