<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://bpms.everteam.us:3005/api/LaunchpointCases/{caseid}/diaries" ID="_AyG50NIJEeecDYn8rNkjbw">
  <rest:operation verb="GET" name="getCaseDiaries" ID="_AyG50tIJEeecDYn8rNkjbw" restservice_type="json">
    <rest:output type="project:///Schemas/integrations/getCaseDiaries.xsd?xsdelement={__project:///Schemas/integrations/getCaseDiaries.xsd}iob_response_root" name="diaries" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_AyG509IJEeecDYn8rNkjbw"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="caseid" headerDirection="request" contentType="text/xml" ID="_AyG50dIJEeecDYn8rNkjbw"/>
</rest:descriptor>