<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://bpms.everteam.us:3005/api/LaunchpointCases/{caseid}/activities?environmentid={environmentid}" ID="_vi1KYNIIEeecDYn8rNkjbw">
  <rest:operation verb="GET" name="getCaseActivities" ID="_vi1KYtIIEeecDYn8rNkjbw" restservice_type="json">
    <rest:output type="project:///Schemas/integrations/getCaseActivities.xsd?xsdelement={__project:///Schemas/integrations/getCaseActivities.xsd}iob_response_root" name="activities" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_vi1KY9IIEeecDYn8rNkjbw"/>
    <rest:fault type="project:///Schemas/integrations/LaunchpointError.xsd?xsdelement={__project:///Schemas/integrations/LaunchpointError.xsd}iob_response_root" name="fault" headerDirection="request" contentType="application/json" ID="_0Xib0NxWEeeFZ-6GsCALZw"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="caseid" headerDirection="request" contentType="text/xml" ID="_vi1KYdIIEeecDYn8rNkjbw"/>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="environmentid" headerDirection="request" contentType="text/xml" ID="_eMqVENxWEeeFZ-6GsCALZw"/>
</rest:descriptor>