<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://bpms.everteam.us:4001/generateFile" ID="_dzJpcLDTEeeORvLgzIAm2A">
  <rest:operation verb="POST" name="generateFile" ID="_dzJpcbDTEeeORvLgzIAm2A" restservice_type="xml">
    <rest:input type="project:///Schemas/GenerateFile.xsd?xsdelement={__project:///Schemas/GenerateFile.xsd}iob_request_root" name="body" headerDirection="request" contentType="application/xml" ID="_dzJpcrDTEeeORvLgzIAm2A"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="response" headerDirection="request" contentType="application/xml" ID="_dzJpc7DTEeeORvLgzIAm2A"/>
  </rest:operation>
</rest:descriptor>