<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://bpms.everteam.us:3005/api/LaunchpointCases/{caseid}?environmentid={environmentid}" ID="_V9YlwNH-EeecDYn8rNkjbw">
  <rest:operation verb="GET" name="getCase" ID="_V9YlwtH-EeecDYn8rNkjbw" restservice_type="json">
    <rest:output type="project:///Schemas/integrations/getLaunchpointCase.xsd?xsdelement={__project:///Schemas/integrations/getLaunchpointCase.xsd}iob_response_root" name="dcmCase" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_V9Ylw9H-EeecDYn8rNkjbw"/>
    <rest:fault type="project:///Schemas/integrations/LaunchpointError.xsd?xsdelement={__project:///Schemas/integrations/LaunchpointError.xsd}iob_response_root" name="fault" headerDirection="request" contentType="applicaton/json" ID="_Ad9lcNwzEeerQrLO1phLEg"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="caseid" headerDirection="request" contentType="text/xml" ID="_V9YlwdH-EeecDYn8rNkjbw"/>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="environmentid" headerDirection="request" contentType="text/xml" ID="_7vwJ4NwyEeerQrLO1phLEg"/>
</rest:descriptor>