<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://www.example.com/" ID="_2m6YMN-dEee0sMeNbhdjFQ">
  <rest:operation verb="POST" name="SendToIso" ID="_2m6YMd-dEee0sMeNbhdjFQ" restservice_type="xml">
    <rest:input type="project:///Schemas/integrations/ISORequest.xsd?xsdelement={__project:///Schemas/integrations/ISORequest.xsd}Cases" name="body" headerDirection="request" contentType="text/xml" ID="_2m6YMt-dEee0sMeNbhdjFQ"/>
    <rest:output type="project:///Schemas/integrations/ISORequest.xsd?xsdelement={__project:///Schemas/integrations/ISORequest.xsd}ACORD" name="response" headerDirection="request" contentType="text/xml" ID="_2m6YM9-dEee0sMeNbhdjFQ"/>
  </rest:operation>
</rest:descriptor>