<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://192.168.241.199:3001/logging" ID="_veMgQKWNEeenuIl8NEN0-Q">
  <rest:operation verb="POST" name="send_log" ID="_veMgQaWNEeenuIl8NEN0-Q" restservice_type="json">
    <rest:input type="project:///Schemas/Logging.xsd?xsdelement={__project:///Schemas/Logging.xsd}iob_request_root" name="body" headerDirection="request" contentType="application/json" requestRootElement="true" ID="_c2qVsKWTEeenuIl8NEN0-Q"/>
    <rest:output type="project:///Schemas/Logging.xsd?xsdelement={__project:///Schemas/Logging.xsd}iob_request_root" name="response" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_veMgQ6WNEeenuIl8NEN0-Q"/>
  </rest:operation>
</rest:descriptor>