<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://BOU-C3DXZ52:8080/logging" ID="_ycoTsKkkEeend6yjaWULFg">
  <rest:operation verb="POST" name="send_log_to_postman" ID="_ycoTtKkkEeend6yjaWULFg" restservice_type="json">
    <rest:input type="project:///Schemas/Logging.xsd?xsdelement={__project:///Schemas/Logging.xsd}iob_request_root" name="body" headerDirection="request" contentType="application/json" requestRootElement="true" ID="_ycoTtakkEeend6yjaWULFg"/>
    <rest:output type="project:///Schemas/Logging.xsd?xsdelement={__project:///Schemas/Logging.xsd}iob_request_root" name="response" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_ycoTtqkkEeend6yjaWULFg"/>
  </rest:operation>
</rest:descriptor>