<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://52.89.71.240:8003/api/v1/loggables" ID="_8WBPkOW9EeeC_M_wrY_Ejg">
  <rest:operation verb="POST" name="tp_log" ID="_8WBPk-W9EeeC_M_wrY_Ejg" restservice_type="json">
    <rest:input type="project:///Schemas/integrations/logger.xsd?xsdelement={__project:///Schemas/integrations/logger.xsd}iob_request_root" name="body" headerDirection="request" contentType="application/json" requestRootElement="true" ID="_8WBPlOW9EeeC_M_wrY_Ejg"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="response" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_8WBPleW9EeeC_M_wrY_Ejg"/>
    <rest:fault type="project:///Schemas/integrations/LaunchpointError.xsd?xsdelement={__project:///Schemas/integrations/LaunchpointError.xsd}iob_response_root" name="fault" headerDirection="request" contentType="application/json" ID="_4esmcOXCEeeC_M_wrY_Ejg"/>
  </rest:operation>
</rest:descriptor>