<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://52.89.71.240:8001/api/v1/activities?EnvironmentId={environmentid}&amp;CaseId={caseid}" ID="_MkGecOAxEeeyeb6h9zFGjQ">
  <rest:operation verb="GET" name="getActivities" ID="_MkGec-AxEeeyeb6h9zFGjQ" restservice_type="json">
    <rest:output type="project:///Schemas/integrations/getCaseActivities.xsd?xsdelement={__project:///Schemas/integrations/getCaseActivities.xsd}iob_response_root" name="activities" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_MkGedOAxEeeyeb6h9zFGjQ"/>
  </rest:operation>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="environmentid" headerDirection="request" contentType="text/xml" ID="_MkGeceAxEeeyeb6h9zFGjQ"/>
  <rest:url type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="caseid" headerDirection="request" contentType="text/xml" ID="_MkGecuAxEeeyeb6h9zFGjQ"/>
</rest:descriptor>