<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://192.168.241.200:3001/sendiso" ID="_u2Py8LBjEeeOOeabhcBaPQ">
  <rest:operation verb="POST" name="Send To ISO" ID="_u2Py8bBjEeeOOeabhcBaPQ" restservice_type="xml">
    <rest:input type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}anyType" name="body" headerDirection="request" contentType="application/xml" ID="_u2Py8rBjEeeOOeabhcBaPQ"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}anyType" name="response" headerDirection="request" contentType="application/xml" ID="_u2Py87BjEeeOOeabhcBaPQ"/>
  </rest:operation>
</rest:descriptor>