<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://bpms.everteam.us:3002/api/iso" ID="_u2Py8LBjEeeOOeabhcBaPQ">
  <rest:operation verb="POST" name="Send To ISO" ID="_u2Py8bBjEeeOOeabhcBaPQ" restservice_type="xml">
    <rest:input type="project:///Schemas/integrations/ISORequest.xsd?xsdelement={__project:///Schemas/integrations/ISORequest.xsd}Wrapper" name="body" headerDirection="request" contentType="application/xml" ID="_u2Py8rBjEeeOOeabhcBaPQ"/>
    <rest:output type="project:///Schemas/integrations/ISORequest.xsd?xsdelement={__project:///Schemas/integrations/ISORequest.xsd}Wrapper" name="response" headerDirection="request" contentType="application/xml" ID="_u2Py87BjEeeOOeabhcBaPQ"/>
  </rest:operation>
</rest:descriptor>