<?xml version='1.0' encoding='UTF-8'?>
<rest:descriptor xmlns:rest="http://www.intalio/designer/business-process-data-modeling/rest" resourceURL="http://192.168.241.200:3001/updatestatus" ID="_AKluILCcEeeBPdzJIpWARQ">
  <rest:operation verb="PUT" name="updateCaseLifecycle" ID="_AKluIbCcEeeBPdzJIpWARQ" restservice_type="json">
    <rest:input type="project:///Schemas/integrations/updateLifecycle.xsd?xsdelement={__project:///Schemas/integrations/updateLifecycle.xsd}iob_request_root" name="body" headerDirection="request" contentType="application/json" requestRootElement="true" ID="_AKluIrCcEeeBPdzJIpWARQ"/>
    <rest:output type="builtin:///xsd?xsdtype={http://www.w3.org/2001/XMLSchema}string" name="response" headerDirection="request" contentType="application/json" responseRootElement="true" ID="_AKluI7CcEeeBPdzJIpWARQ"/>
  </rest:operation>
</rest:descriptor>