-- drop view public."ISOCases";
CREATE OR REPLACE VIEW public."ISOCases" AS
 SELECT DISTINCT casetracking.batchid,
    casetracking.pid AS parentpid,
    isotracking.pid AS isopid,
    casetracking.caseid,
    casetracking.isoindicator,
    casetracking.score,
    casetracking.accidentdate,
    casetracking.benefitamount,
    casetracking.fundingsource,
    casetracking.lob,
    casetracking.state,
    casetracking.workcomp,
    casetracking.casestatus,
    casetracking.casesource,
    casetracking.casetype,
    casetracking.casereceived,
    casetracking.caseidentified,
    casetracking.casereceivedat,
    casetracking.caseidentifiedat,
    isotracking.requestid,
    isotracking.isoreceived,
    isotracking.isoreceivedat,
    isotracking.isoprocessingbegan,
    isotracking.isoprocessingbeganat,
    isotracking.isoduplicatefound,
    isotracking.isoduplicatefoundat,
    isotracking.isodatafetched,
    isotracking.isodatafetchedat,
    isotracking.isosent,
    isotracking.isosentat
   FROM casetracking
     JOIN isotracking ON casetracking.caseid = isotracking.caseid
  WHERE isotracking.parentpid = casetracking.pid AND casetracking.casetype::text = 'ISO'::text;