<wsdl:definitions targetNamespace="http://bpms.everteam.com/LaunchPointProcess" xmlns:tns="http://bpms.everteam.com/LaunchPointProcess" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:ns="http://bpms.everteam.com/LaunchPointProcess">
	<wsdl:types>
		<xsd:schema targetNamespace="http://bpms.everteam.com/LaunchPointProcess"
			elementFormDefault="qualified" attributeFormDefault="unqualified">
			<xsd:element name="StartTimer">
				<xsd:complexType>
					<xsd:sequence/>
				</xsd:complexType>
			</xsd:element>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="StartTimer_Input">
		<wsdl:part name="parameters" element="tns:StartTimer"/>
	</wsdl:message>
	<wsdl:portType name="StartTimer_Port">
		<wsdl:operation name="StartTimer">
			<wsdl:input message="tns:StartTimer_Input"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="StartTimer_Port_SoapBinding" type="tns:StartTimer_Port">
		<soap:binding style="document"
			transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="StartTimer">
			<soap:operation soapAction="StartTimer"/>
			<wsdl:input>
				<soap:body namespace="http://bpms.everteam.com/LaunchPointProcess" use="literal"/>
			</wsdl:input>
		</wsdl:operation>
	</wsdl:binding>
</wsdl:definitions>