-- External variable database definition for PostGres 
-- Generated 10/13/17 11:09 PM
-- Descriptor: Metrics/metrics.xvar (currently edited)
-- External variable ISOResponseTracking
DROP TABLE IF EXISTS ISOResponseTracking;
CREATE TABLE ISOResponseTracking (PID VARCHAR(250), REQUESTID VARCHAR(250), CASEID VARCHAR(250), SCORE VARCHAR(250), RESPONSESTATE VARCHAR(250), SENTDCMRESPONSE TIMESTAMP, RECEIVEDSCORE TIMESTAMP, CREATEDDIARY TIMESTAMP, UPDATEDCASE TIMESTAMP, PDID VARCHAR(250), CREATEDAT TIMESTAMP, UPDATEDAT TIMESTAMP);
CREATE INDEX ISOResponseTracking_KEYS ON ISOResponseTracking (PID);
-- External variable ISOTracking
DROP TABLE IF EXISTS ISOTracking;
CREATE TABLE ISOTracking (PID VARCHAR(250), CASEID VARCHAR(250), REQUESTID VARCHAR(250), CASESTATE VARCHAR(250), RECEIVEDISO TIMESTAMP, BEGANISOPROCESSING TIMESTAMP, FOUNDDUPLICATEISO TIMESTAMP, FETCHEDISODATA TIMESTAMP, SENTTOISO TIMESTAMP, PDID VARCHAR(250), CREATEDAT TIMESTAMP, MODIFIEDAT TIMESTAMP);
CREATE INDEX ISOTracking_KEYS ON ISOTracking (PID);
-- External variable CaseTracking
DROP TABLE IF EXISTS CaseTracking;
CREATE TABLE CaseTracking (PID VARCHAR(250), CASEID VARCHAR(250), ISOINDICATOR INTEGER, SCORE INTEGER, ACCIDENTDATE TIMESTAMP, BENEFITAMOUNT VARCHAR(250), FUNDINGSOURCE VARCHAR(250), LOB VARCHAR(250), STATE VARCHAR(250), WORKCOMP VARCHAR(250), CASESTATUS VARCHAR(250), CASESOURCE VARCHAR(250), CASETYPE VARCHAR(250), BATCHID VARCHAR(250), CASESTATE VARCHAR(250), RECEIVEDCASE TIMESTAMP, IDENTIFIEDCASE TIMESTAMP, PDID VARCHAR(250), CREATEDAT TIMESTAMP, MODIFIEDAT TIMESTAMP);
CREATE INDEX CaseTracking_KEYS ON CaseTracking (PID);
-- External variable BatchTracking
DROP TABLE IF EXISTS BatchTracking;
CREATE TABLE BatchTracking (BATCHID VARCHAR(250), ENVIRONMENTID VARCHAR(250), CLIENTID VARCHAR(250), CASECOUNT INTEGER, BATCHSTATUS VARCHAR(250), CREATEDAT TIMESTAMP, MODIFIEDAT TIMESTAMP, RECEIVEDAT TIMESTAMP, PROCESSINGFINISHEDAT TIMESTAMP, PID BIGINT, PDID VARCHAR);
CREATE INDEX BatchTracking_KEYS ON BatchTracking (BATCHID);

